const authorSeeds = [
  {
    name: "Lucy Score",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Tamsyn Muir",
    gender: "Woman",
    race: "White",
    nationality: "New Zealander",
  },
  {
    name: "Rick Riordan",
    gender: "Man",
    race: "White",
    nationality: "American",
  },
  {
    name: "Bessel Van Der Kolk",
    gender: "Man",
    race: "White",
    nationality: "Dutch",
  },
  {
    name: "L.J. Shen",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },

  {
    name: "Zoraida Córdova",
    gender: "Woman",
    race: "Hispanic",
    nationality: "Ecuadorian",
  },
  {
    name: "Lulu Miller",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Sophie Lark",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Stephanie Foo",
    gender: "Woman",
    race: "Asian",
    nationality: "Malaysian",
  },
  {
    name: "Jayne Allen",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Tommy Orange",
    gender: "Man",
    race: "Native",
    nationality: "American",
  },
  {
    name: "Annabel Monaghan",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Bonnie Garmus",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Casey McQuiston",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Neal D. Barnard, M.D.",
    gender: "Man",
    race: "White",
    nationality: "American",
  },
  {
    name: "Shannon Chakraborty",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Keigo Higashino",
    gender: "Man",
    race: "Asian",
    nationality: "Japanese",
  },
  {
    name: "Kristin Cashore",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "N.K. Jemisin",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Rebecca Yarros",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Mikki Kendall",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Emily St. John Mandel",
    gender: "Woman",
    race: "White",
    nationality: "Canadian",
  },
  {
    name: "Caroline Criado Perez",
    gender: "Woman",
    race: "White",
    nationality: "British",
  },
  {
    name: "Nguyễn Phan Quế Mai",
    gender: "Woman",
    race: "Asian",
    nationality: "Vietnamese",
  },
  {
    name: "Louise Erdich",
    gender: "Woman",
    race: "Native",
    nationality: "American",
  },
  {
    name: "Samantha Shannon",
    gender: "Woman",
    race: "White",
    nationality: "British",
  },
  {
    name: "Rachel Gillig",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Denise Kiernan",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Gail Carson Levine",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Tracy Deonn",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Suzanne Simard",
    gender: "Woman",
    race: "White",
    nationality: "Canadian",
  },
  {
    name: "Angela Y. Davis",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Hope Jahren",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Gabrielle Zevin",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Jasmine Guillory",
    race: "Black",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Sally Rooney",
    race: "White",
    gender: "Woman",
    nationality: "Irish",
  },
  {
    name: "Annie Proulx",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Akwaeke Emezi",
    race: "Black",
    gender: "Woman",
    nationality: "Nigerian",
  },
  {
    name: "Michelle Zauner",
    race: "Asian",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "George R.R. Martin",
    race: "White",
    gender: "Man",
    nationality: "American",
  },
  {
    name: "Kiley Reid",
    race: "Black",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Amal El-Mohtar & Max Gladstone",
    race: "?/White",
    gender: "Woman/Man",
    nationality: "Canadian/American",
  },
  {
    name: "Delia Owens",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Lauren Groff",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Jane Austen",
    race: "White",
    gender: "Woman",
    nationality: "British",
  },
  {
    name: "Julia Whelan",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Shelby Van Pelt",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Julia Quinn",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Laura Dave",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Julie Murphy",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Steven Rowley",
    race: "White",
    gender: "Man",
    nationality: "American",
  },
  {
    name: "Linda Holmes",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Alison Larkin",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Ijeoma Oluo",
    race: "Black",
    gender: "Woman",
    nationality: "British",
  },
  {
    name: "Jenny Lawson",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Jack Harbon",
    race: "Black",
    gender: "Man",
    nationality: "American",
  },
  {
    name: "Nikki Payne",
    race: "Black",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Sarah Kozloff",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Taylor Reid Jenkins",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Colleen Hoover",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Alix E. Harrow",
    race: "White",
    gender: "Woman",
    nationality: "American",
  },
  {
    name: "Grady Hendrix",
    race: "White",
    gender: "Man",
    nationality: "American",
  },
  {
    name: "Viola Davis",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Alex Aster",
    gender: "Woman",
    race: "Columbian",
    nationality: "American",
  },
  {
    name: "Julie Soto",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Jessica Joyce",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Chanel Miller",
    gender: "Woman",
    race: "Chinese-White",
    nationality: "American",
  },
  {
    name: "Miranda July",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Natasha Bishop",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "TJ Klune",
    gender: "Man",
    race: "White",
    nationality: "American",
  },
  {
    name: "Terah Shelton Harris",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Maria Bamford",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Hannah Nicole Maehrer",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Candice Carty-Williams",
    gender: "Woman",
    race: "Black",
    nationality: "British",
  },
  {
    name: "Isabel Ibañez",
    gender: "Woman",
    race: "Hispanic",
    nationality: "Bolivian",
  },
  {
    name: "Chimamanda Ngozi Adiche",
    gender: "Woman",
    race: "African",
    nationality: "Nigerian",
  },
  {
    name: "Breanne Randall",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Merlin Sheldrake",
    gender: "Man",
    race: "White",
    nationality: "British",
  },
  {
    name: "Helen Hoang",
    gender: "Woman",
    race: "Asian",
    nationality: "American",
  },
  {
    name: "Jill Ciment",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Kevin Wilson",
    gender: "Man",
    race: "White",
    nationality: "American",
  },
  {
    name: "James Herriot",
    gender: "Man",
    race: "White",
    nationality: "British",
  },
  {
    name: "Emily Habeck",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Mira Jacob",
    gender: "Woman",
    race: "Indian",
    nationality: "American",
  },
  {
    name: "Lauren Roberts",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Safiya Sinclair",
    gender: "Woman",
    race: "Black",
    nationality: "Jamaican",
  },
  {
    name: "Frank Abe",
    gender: "Man",
    race: "Asian",
    nationality: "Japanese",
  },
  {
    name: "Susanna Clarke",
    gender: "Woman",
    race: "White",
    nationality: "British",
  },
  {
    name: "T. Kingfisher",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Trevor Noah",
    gender: "Man",
    race: "Black",
    nationality: "South African",
  },
  {
    name: "Amy Tan",
    gender: "Woman",
    race: "Chinese",
    nationality: "American",
  },
  {
    name: "Marie-Helene Bertino",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Heather Fawcett",
    gender: "Woman",
    race: "White",
    nationality: "Canadian",
  },
  {
    name: "Stephanie Land",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "M.R. Carey",
    gender: "Man",
    race: "White",
    nationality: "British",
  },
  {
    name: "Natalie Sue",
    gender: "Woman",
    race: "Iranian",
    nationality: "Canadian",
  },
  {
    name: "P. Djeli Clark",
    gender: "Man",
    race: "African",
    nationality: "American",
  },
  {
    name: "Kristin Hannah",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Emily Nagoski",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Martha Wells",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Ellery Lloyd",
    gender: "Man/Woman",
    race: "White",
    nationality: "British",
  },
  {
    name: "Christina Lauren",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Tia Williams",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Nita Prose",
    gender: "Woman",
    race: "White",
    nationality: "Canadian",
  },
  {
    name: "Sally Thorne",
    gender: "Woman",
    race: "White",
    nationality: "Australian",
  },

  {
    name: "Sophie Cousens",
    gender: "Woman",
    race: "White",
    nationality: "English",
  },
  {
    name: "Denise Williams",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "India Holton",
    gender: "Woman",
    race: "White",
    nationality: "New Zealander",
  },
  {
    name: "Jesmyn Ward",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Xochitl Gonzalez",
    gender: "Woman",
    race: "Hispanic",
    nationality: "American",
  },
  {
    name: "Lynn Painter",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Deanna Raybourn",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Abby Jimenez",
    gender: "Woman",
    race: "Hispanic",
    nationality: "American",
  },
  {
    name: "Curtis Sittenfeld",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Ana Huang",
    gender: "Woman",
    race: "Asian",
    nationality: "American",
  },
  {
    name: "Tessa Bailey",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Beth O'Leary",
    gender: "Woman",
    race: "White",
    nationality: "English",
  },
  {
    name: "Mia Sosa",
    gender: "Woman",
    race: "Latinx",
    nationality: "American",
  },
  {
    name: "Sarah Hogle",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Sarah J. Maas",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "R.F. Kuang",
    gender: "Woman",
    race: "Asian",
    nationality: "Chinese",
  },
  {
    name: "Leigh Bardugo",
    gender: "Woman",
    race: "White",
    nationality: "Israeli",
  },
  {
    name: "Rebecca Serle",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Rebecca Ross",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Elena Armas",
    gender: "Woman",
    race: "Hispanic",
    nationality: "Spanish",
  },
  {
    name: "Elissa Sussman",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Talia Hibbert",
    gender: "Woman",
    race: "Black",
    nationality: "British",
  },
  {
    name: "Jonathan Stroud",
    gender: "Man",
    race: "White",
    nationality: "British",
  },
  {
    name: "Lauren Asher",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Fredrik Backman",
    gender: "Man",
    race: "White",
    nationality: "Swedish",
  },
  {
    name: "Olivia Dade",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Dr. Paul Kalanithi",
    gender: "Man",
    race: "Indian",
    nationality: "American",
  },
  {
    name: "Marissa Meyer",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Sierra Godfrey",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Monica Heisey",
    gender: "Woman",
    race: "White",
    nationality: "Canadian",
  },
  {
    name: "Rebecca Makkai",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "V.E. Schwab",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Dana Scwartz",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Ava Wilder",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Jackie Fraser",
    gender: "Woman",
    race: "White",
    nationality: "British",
  },
  {
    name: "Kristen Cashore",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Sarah J. Mass",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Weike Wang",
    gender: "Woman",
    race: "Asian",
    nationality: "American",
  },
  {
    name: "Ottessa Moshfegh",
    gender: "Woman",
    race: "Middle Eastern",
    nationality: "American",
  },
  {
    name: "Tiffany Haddish",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Angeline Boulley",
    gender: "Woman",
    race: "Native",
    nationality: "American",
  },
  {
    name: "Uzma Jalaluddin",
    gender: "Woman",
    race: "Middle Eastern",
    nationality: "American",
  },
  {
    name: "Ashley Poston",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Katherine Center",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },
  {
    name: "Stephanie Meyer",
    gender: "Woman",
    race: "White",
    nationality: "American",
  },

  {
    name: "Kurt Vonnegut",
    gender: "Man",
    race: "White",
    nationality: "American",
  },
  {
    name: "bell hooks",
    gender: "Woman",
    race: "Black",
    nationality: "American",
  },
  {
    name: "Kristiana Kahakauwila",
    gender: "Woman",
    race: "Hawaiian",
    nationality: "Hawaiian",
  },
];

module.exports = { authorSeeds };
