const rereads = [
  {
    title: "Fire",
    author: "Kristen Cashore",
    genre: ["Fantasy", "YA"],
    rating: 5,
    reread: true,
    yearPublished: 2009,
    dateStarted: "10/26/23",
    dateFinished: "10/29/23",
    readingFormat: "Audiobook",
    pageCount: 480,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: ["Fantasy", "Children's/Middle Reader"],
    rating: 5,
    reread: true,
    yearPublished: 1997,
    dateStarted: "09/28/24",
    dateFinished: "10/19/24",
    readingFormat: "Book",
    pageCount: 333,
  },
  {
    title: "System Collapse",
    author: "Martha Wells",
    genre: ["SciFi"],
    rating: 3,
    reread: false,
    yearPublished: 2023,
    dateStarted: "10/19/23",
    dateFinished: "10/20/23",
    readingFormat: "Audiobook",
    pageCount: 256,
  }
];
