const rereads = [

      {
        title: "People We Meet on Vacation",
        author: "Emily Henry",
        genre: ["Romance", "Fiction"],
        rating: 4,
        reread: true,
        yearPublished: 2021,
        dateStarted: "",
        dateFinished: "1/6/22",
        readingFormat: "Audiobook",
        pageCount: 364,
      },
      {
        title: "Love on the Brain",
        author: "Ali Hazelwood",
        genre: ["Romance"],
        rating: 5,
        reread: true,
        yearPublished: 2022,
        dateStarted: "",
        dateFinished: "3/14/23",
        readingFormat: "Audiobook",
        pageCount: 368,
      },
      {
        title: "A Court of Thorns and Roses",
        author: "Sarah J. Maas",
        genre: ["Fantasy", "Romance"],
        rating: 2,
        reread: true,
        yearPublished: 2015,
        dateStarted: "9/19/23",
        dateFinished: "9/22/23",
        readingFormat: "Audiobook",
        pageCount: 419,
      },
 
      {
        title: "A Court of Wings and Ruin",
        author: "Sarah J. Maas",
        genre: ["Fantasy"],
        rating: 3,
        reread: true,
        yearPublished: 2017,
        dateStarted: "9/24/23",
        dateFinished: "9/29/23",
        readingFormat: "Audiobook",
        pageCount: 703,
      },
      {
        title: "A Court of Silver Flames",
        author: "Sarah J. Maas",
        genre: ["Fantasy", "Romance"],
        rating: 4,
        reread: true,
        yearPublished: 2021,
        dateStarted: "10/3/23",
        dateFinished: "10/8/23",
        readingFormat: "Audiobook",
        pageCount: 757,
      },
      {
        title: "Yours Truly",
        author: "Abby Jimenez",
        genre: ["Romance", "Fiction"],
        rating: 5,
        reread: true,
        yearPublished: 2023,
        dateStarted: "10/23/23",
        dateFinished: "10/26/23",
        readingFormat: "Audiobook",
        pageCount: 416,
      },
      {
        title: "Fire",
        author: "Kristen Cashore",
        genre: ["Fantasy", "YA"],
        rating: 5,
        reread: true,
        yearPublished: 2009,
        dateStarted: "10/26/23",
        dateFinished: "10/29/23",
        readingFormat: "Audiobook",
        pageCount: 480,
      },
      {
        title: "Vicious",
        author: "L.J. Shen",
        genre: ["Romance"],
        rating: 4,
        reread: true,
        yearPublished: 2016,
        dateStarted: "",
        dateFinished: "3/22/23",
        readingFormat: "Book",
        pageCount: 339,
      },
      {
        title: "Love, Theoretically",
        author: "Ali Hazelwood",
        genre: ["Romance"],
        rating: 3,
        reread: true,
        yearPublished: 2023,
        dateStarted: "10/16/23",
        dateFinished: "10/19/23",
        readingFormat: "Book",
        pageCount: 389,
      },
      {
        title: "Yours Truly",
        author: "Abby Jiminez",
        genre: ["Romance", "Fiction"],
        rating: 5,
        reread: true,
        yearPublished: 2023,
        dateStarted: "12/11/23",
        dateFinished: "12/12/23",
        readingFormat: "Book",
        pageCount: 416,
      },
      {
        title: "Yours Truly",
        author: "Abby Jiminez",
        genre: ["Romance", "Fiction"],
        rating: 5,
        reread: true,
        yearPublished: 2023,
        dateStarted: "4/18/24",
        dateFinished: "4/19/24",
        readingFormat: "Audiobook",
        pageCount: 416,
      },
      {
        title: "Love on the Brain",
        author: "Ali Hazelwood",
        genre: ["Romance"],
        rating: 5,
        reread: true,
        yearPublished: 2022,
        dateStarted: "4/20/24",
        dateFinished: "4/25/24",
        readingFormat: "Book",
        pageCount: 368,
      },
      {
        title: "Love in Color",
        author: "Bolu Babalola",
        genre: ["Mythology", "Romance"],
        rating: 3,
        reread: true,
        yearPublished: 2020,
        dateStarted: "4/22/24",
        dateFinished: "4/24/24",
        readingFormat: "Audiobook",
        pageCount: 290,
      },
      {
        title: "Part of Your World",
        author: "Abby Jiminez",
        genre: ["Romance", "Fiction"],
        rating: 5,
        reread: true,
        yearPublished: 2022,
        dateStarted: "4/22/24",
        dateFinished: "4/23/24",
        readingFormat: "Audiobook",
        pageCount: 400,
      },
      {
        title: "Out on a Limb",
        author: "Hannah Bonham-Young",
        genre: ["Romance"],
        rating: 4,
        reread: true,
        yearPublished: 2023,
        dateStarted: "4/26/24",
        dateFinished: "4/29/24",
        readingFormat: "Audiobook",
        pageCount: 397,
      },
      {
        title: "Yours Truly",
        author: "Abby Jiminez",
        genre: ["Romance", "Fiction"],
        rating: 5,
        reread: true,
        yearPublished: 2023,
        dateStarted: "7/11/24",
        dateFinished: "7/12/24",
        readingFormat: "Audiobook",
        pageCount: 416,
      },
      {
        title: "People We Meet On Vacation",
        author: "Emily Henry",
        genre: ["Romance", "Fiction"],
        rating: 4,
        reread: true,
        yearPublished: 2021,
        dateStarted: "8/9/24",
        dateFinished: "8/12/24",
        readingFormat: "Audiobook",
        pageCount: 364,
      },
      {
        title: "Fourth Wing",
        author: "Rebecca Yarros",
        genre: ["Fantasy", "Romance"],
        rating: 4,
        reread: true,
        yearPublished: 2023,
        dateStarted: "8/27/24",
        dateFinished: "8/29/24",
        readingFormat: "Audiobook",
        pageCount: 517,
      },
      {
        title: "Iron Flame",
        author: "Rebecca Yarros",
        genre: ["Fantasy"],
        rating: 3,
        reread: true,
        yearPublished: 2023,
        dateStarted: "8/29/24",
        dateFinished: "9/4/24",
        readingFormat: "Audiobook",
        pageCount: 640,
      },
      {
        title: "The Love Hypothesis",
        author: "Ali Hazelwood",
        genre: ["Romance"],
        rating: 4,
        reread: true,
        yearPublished: 2021,
        dateStarted: "",
        dateFinished: "3/17/23",
        readingFormat: "Audiobook",
        pageCount: 383,
      },
]